name: Gatsby DevOps
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature/*
jobs:
  Install_Dependencies:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.sha }}
      - run: npm ci
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - run: sed -i "s/%%VERSION%%/${{ github.sha }}/g" ./public/index.html
      - run: echo ${{github.event_name}}
      - name: Upload built public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public

