name: Gatsby DevOps
on: [push]
jobs:
  Install_Dependencies:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm install -g gatsby-cli
      - run: gatsby build