name: Gatsby DevOps
on: [push]
jobs:
  Install_Dependencies:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - name: Upload built public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
  Test_artifact:
    container: node:16
    runs-on: ubuntu-latest
    needs: [Install_Dependencies]
    steps:
      - name: Download public folder
        uses: actions/download-artifact@v3
        with:
          name: public
      - run: ls -la
      - run: grep "Gatsby" ./public/index.html
      - run: grep "XXXXXXXX" ./public/index.html
