name: Gatsby DevOps
on: [push]
jobs:
  Install_Dependencies:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm install -g gatsby-cli
      - run: gatsby build