name: Gatsby DevOps
on: [push]
jobs:
  Install_Dependencies:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.sha }}
      - run: npm ci
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - run: sed -i "s/%%VERSION%%/${{ github.sha }}/g" ./public/index.html
      - name: Upload built public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
  Test_artifact:
    container: alpine
    runs-on: ubuntu-latest
    needs: [Install_Dependencies]
    steps:
      - name: Download public folder
        uses: actions/download-artifact@v3
        with:
          name: public
      - run: grep "Gatsby" ./index.html
  Deploy_staging:
    env:
      name: staging
      url: http://Quibox-staging.surge.sh
    container: node:16
    runs-on: ubuntu-latest
    needs: [ Install_Dependencies ]
    steps:
      - name: Download public folder
        uses: actions/download-artifact@v3
        with:
          name: public
      - name: Deploy to Quibox-staging.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'Quibox-staging.surge.sh'
          project: '.'
          login: ${{secrets.surge_login}}
          token: ${{secrets.surge_token}}
  Deploy_production:
    env:
      name: production
      url: http://Quibox.surge.sh
    container: node:16
    runs-on: ubuntu-latest
    needs: [Install_Dependencies]
    steps:
      - name: Download public folder
        uses: actions/download-artifact@v3
        with:
          name: public
      - name: Deploy to Quibox.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'Quibox.surge.sh'
          project: '.'
          login: ${{secrets.surge_login}}
          token: ${{secrets.surge_token}}
  test deployment:
    container: alpine
    runs-on: ubuntu-latest
    needs: [Deploy_production]
    steps:
      - run: apk --no-cache add curl
      - run: echo curl --version
      - run: curl "https://quibox.surge.sh" | tac | tac | grep -q "Gatsby"

